author: Storesense
url: http://storesense.info/
title: storesense

defaults:
  -
    scope:
      path: ""
    values:
      type: "expo"

  -
    scope:
      path: "storesense"
    values:
      type: "storesense"
